SUPABASE_URL : http://127.0.0.1:54321
DATABASE_URL: postgresql//postgres:postgres@localhost:54322/postgres
JDBC_URL : jdbc:postgresql://postgres:postgres@localhost:54322/postgres
SUPABASE_ANON_KEY :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_KEY : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
SPARK_JAR : /path/to/postgresql-42.7.3.jar

USER : postgres
PASSWORD : postgres
DRIVER : org.postgresql.Driver

# ML Models
EMBEDDING_MODEL : all-MiniLM-L6-v2
LLM_MODEL: ollama/llama2

# API Configuration
API_HOST: 0.0.0.0
API_PORT: 8000

# Development
DEBUG: True
LOG_LEVEL: info